# Generated by Django 2.0.1 on 2018-03-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0010_auto_20180306_2157'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to='ingresos.Company'),
        ),
    ]
