# Generated by Django 2.0.1 on 2018-03-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_itemalmacen_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalmacen',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.Almacen'),
        ),
    ]
