# Generated by Django 2.0 on 2018-01-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price',
        ),
    ]
