# Generated by Django 2.0 on 2018-01-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egress',
            new_name='Egres',
        ),
    ]
