# Generated by Django 2.0 on 2018-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_auto_20180102_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='egres',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
