# Generated by Django 2.0.1 on 2018-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_purchase_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='credit',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
