# Generated by Django 2.0 on 2018-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0003_egres_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egres',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
