# Generated by Django 2.0.1 on 2018-08-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0003_provider_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
