# Generated by Django 2.0 on 2018-01-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0004_auto_20180102_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egres',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
