# Generated by Django 2.0.1 on 2018-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0006_provider_rfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='contact_check',
        ),
        migrations.AddField(
            model_name='provider',
            name='contact',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_check',
            field=models.BooleanField(default=False),
        ),
    ]
