# Generated by Django 2.0 on 2018-01-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0006_auto_20180102_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='provider',
            new_name='provid',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='uprice',
        ),
    ]
