# Generated by Django 2.0 on 2018-01-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0007_auto_20180102_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='provid',
            new_name='provider',
        ),
    ]
