# Generated by Django 2.0.1 on 2018-02-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0008_auto_20180216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(blank=True, choices=[('Gasto', 'Gasto'), ('Costo', 'Costo')], max_length=100, null=True),
        ),
    ]
