# Generated by Django 2.0.1 on 2018-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0009_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='rfc',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
