# Generated by Django 2.0.1 on 2018-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0015_auto_20180509_2109'),
        ('egresos', '0012_auto_20180508_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='business_line',
        ),
        migrations.AddField(
            model_name='purchase',
            name='business_line',
            field=models.ManyToManyField(related_name='purchases', to='ingresos.BusinessLine'),
        ),
    ]
