# Generated by Django 2.0.1 on 2018-05-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0013_auto_20180509_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='business_line',
        ),
        migrations.AddField(
            model_name='purchase',
            name='business_line',
            field=models.CharField(blank=True, choices=[('Cerdos', 'Cerdos'), ('Ganado', 'Ganado'), ('Granos', 'Granos'), ('Planta de alimentos', 'Planta de alimentos'), ('Campo', 'Campo')], max_length=100, null=True),
        ),
    ]
