# Generated by Django 2.0.1 on 2018-05-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0015_auto_20180510_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='egresos.Provider'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='egresos.Purchase'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='egresos.Product'),
        ),
    ]
