# Generated by Django 2.0.1 on 2018-05-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0016_auto_20180518_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='ingresos.BusinessLine'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='egresos.Provider'),
        ),
    ]
