# Generated by Django 2.0.1 on 2018-05-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0016_auto_20180518_2034'),
        ('egresos', '0016_auto_20180515_2121'),
    ]

    operations = [
    ]
