# Generated by Django 2.0.1 on 2018-05-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0017_auto_20180523_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='business_line',
            new_name='business_egreso',
        ),
    ]
