# Generated by Django 2.0.1 on 2018-05-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0018_auto_20180523_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='provider',
            new_name='provider_egreso',
        ),
    ]
