# Generated by Django 2.0.1 on 2018-05-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0022_remove_saleitem_product'),
        ('egresos', '0019_auto_20180523_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_factura', models.CharField(max_length=140)),
                ('descripcion', models.CharField(max_length=140)),
                ('fecha_creacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concepto_compras', models.CharField(blank=True, max_length=140, null=True)),
                ('linea_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='ingresos.BusinessLine')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='egresos.Provider')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='concepto_purchase',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
