# Generated by Django 2.0.1 on 2018-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0021_remove_compras_concepto_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha_creacion',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
