# Generated by Django 2.0.1 on 2018-05-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0022_auto_20180523_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='compra_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='egresos.Compras'),
        ),
    ]
