# Generated by Django 2.0.1 on 2018-05-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0023_purchase_compra_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='compra_check',
            field=models.BooleanField(default=False),
        ),
    ]
