# Generated by Django 2.0.1 on 2018-05-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0017_merge_20180522_1759'),
        ('egresos', '0024_purchase_compra_check'),
    ]

    operations = [
    ]
