# Generated by Django 2.0.1 on 2018-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0024_purchase_compra_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoGanado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=140)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
    ]
