# Generated by Django 2.0.1 on 2018-05-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0025_merge_20180525_1857'),
        ('egresos', '0025_gastoganado'),
    ]

    operations = [
    ]
