# Generated by Django 2.0.1 on 2018-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_point', '0002_auto_20180514_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
