# Generated by Django 2.0.1 on 2018-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_point', '0003_auto_20180515_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
