# Generated by Django 2.0.1 on 2018-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_point', '0004_auto_20180515_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
