# Generated by Django 2.0.1 on 2018-05-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_point', '0005_product_unity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
    ]
