# Generated by Django 2.0.1 on 2018-01-29 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='ingresos.Client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('Tarjeta Credito', 'Tarjeta Credito'), ('Efectivo', 'Efectivo'), ('Tarjeta Debito', 'Tarjeta Debito')], max_length=100),
        ),
    ]
