# Generated by Django 2.0 on 2018-01-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='egresos.Product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
