# Generated by Django 2.0.1 on 2018-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_auto_20180129_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='kg_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='units',
        ),
        migrations.AddField(
            model_name='sale',
            name='business_line',
            field=models.CharField(blank=True, choices=[('Cerdos', 'Cerdos'), ('Ganado', 'Ganado'), ('Granos', 'Granos'), ('Planta de alimentos', 'Planta de alimentos'), ('Campo', 'Campo')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='no_scheck',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_check',
            field=models.BooleanField(default=False),
        ),
    ]
