# Generated by Django 2.0 on 2018-01-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_auto_20180103_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='order',
            new_name='sale',
        ),
    ]
