# Generated by Django 2.0.1 on 2018-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_auto_20180707_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
