# Generated by Django 2.0.1 on 2018-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_auto_20180212_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
