# Generated by Django 2.0.1 on 2018-02-26 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0008_auto_20180216_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=140)),
                ('line_comp', models.CharField(blank=True, choices=[('Cerdos', 'Cerdos'), ('Ganado', 'Ganado'), ('Granos', 'Granos'), ('Planta de alimentos', 'Planta de alimentos'), ('Campo', 'Campo')], max_length=100, null=True)),
                ('rfc_comp', models.CharField(default='', max_length=20, unique=True)),
                ('email_comp', models.EmailField(max_length=254)),
                ('phone_compa', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en el formato: '7751234567'. Hasta 10 dígitos permitidos.", regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
