# Generated by Django 2.0.1 on 2018-03-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0009_auto_20180226_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='line_comp',
        ),
        migrations.AddField(
            model_name='company',
            name='line_comp',
            field=models.ManyToManyField(related_name='companies', to='ingresos.BusinessLine'),
        ),
    ]
