# Generated by Django 2.0.1 on 2018-05-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0010_auto_20180306_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
    ]
