# Generated by Django 2.0.1 on 2018-05-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0011_auto_20180504_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessline',
            options={'ordering': ['-id']},
        ),
    ]
