# Generated by Django 2.0.1 on 2018-05-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0012_auto_20180507_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
    ]
