# Generated by Django 2.0.1 on 2018-05-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0013_auto_20180507_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id']},
        ),
    ]
