# Generated by Django 2.0.1 on 2018-05-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0014_auto_20180509_2157'),
        ('ingresos', '0015_auto_20180509_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='animal_ref',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='egresos.Product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='weigth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
