# Generated by Django 2.0.1 on 2018-05-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0017_auto_20180510_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('banco', models.CharField(blank=True, max_length=140, null=True)),
                ('clabe', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='concepto',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ingresos.Client'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='egresos.Product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ingresos.Sale'),
        ),
    ]
