# Generated by Django 2.0.1 on 2018-05-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0018_auto_20180518_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='clabe',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='cuenta',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
