# Generated by Django 2.0.1 on 2018-05-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0018_auto_20180515_2121'),
        ('ingresos', '0020_sale_receivable'),
    ]

    operations = [
    ]
