# Generated by Django 2.0.1 on 2018-05-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0022_remove_saleitem_product'),
        ('ingresos', '0021_merge_20180522_1759'),
    ]

    operations = [
    ]
