# Generated by Django 2.0.1 on 2018-07-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_sale_comment'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almacén',
            new_name='Almacen',
        ),
    ]
