# Generated by Django 2.0.1 on 2018-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
        ('planta_alimentos', '0002_auto_20180131_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='provider',
            field=models.ManyToManyField(blank=True, null=True, related_name='insumos', to='egresos.Provider'),
        ),
    ]
