# Generated by Django 2.0.1 on 2018-02-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
        ('planta_alimentos', '0003_insumo_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='provider',
        ),
        migrations.AddField(
            model_name='insumo',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='egresos.Provider'),
        ),
    ]
