# Generated by Django 2.0.1 on 2018-02-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_alimentos', '0004_auto_20180206_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='unit',
        ),
    ]
