# Generated by Django 2.0.1 on 2018-02-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_alimentos', '0005_remove_insumo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='loading_maneuver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
