# Generated by Django 2.0.1 on 2018-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_alimentos', '0006_auto_20180209_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unit_price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
