# Generated by Django 2.0.1 on 2018-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta_alimentos', '0007_insumo_unit_price_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='percentage',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='formula',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='formula',
            name='total_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
