# Generated by Django 2.0.1 on 2018-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta_alimentos', '0008_auto_20180214_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['-id']},
        ),
    ]
