# Generated by Django 2.0.1 on 2018-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='profile',
            name='aves',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección del aves'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cerdos',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección del cerdos'),
        ),
    ]
