# Generated by Django 2.0.1 on 2018-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección administrativa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ganado',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección del Ganado'),
        ),
    ]
