# Generated by Django 2.0.1 on 2018-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180514_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alimentos',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección del alimentos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacunas',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección de vacunas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vendedor',
            field=models.BooleanField(default=False, help_text='Selecciona si este usuario usará la sección de Ventas'),
        ),
    ]
