# Generated by Django 2.0.1 on 2018-02-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=100)),
            ],
        ),
    ]
