# Generated by Django 2.0.1 on 2018-03-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_auto_20180227_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacuna',
            old_name='type',
            new_name='typeof',
        ),
    ]
