# Generated by Django 2.0.1 on 2018-03-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0004_vacuna_unity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacuna',
            old_name='typeof',
            new_name='typeofv',
        ),
    ]
