# Generated by Django 2.0 on 2018-01-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='ganado.Alimento'),
        ),
    ]
