# Generated by Django 2.0.1 on 2018-08-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FierroN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fierros/n')),
            ],
        ),
        migrations.CreateModel(
            name='FierroO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fierros/o')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='fierroN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='ganado.FierroN'),
        ),
        migrations.AddField(
            model_name='animal',
            name='fierroO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='ganado.FierroO'),
        ),
    ]
