# Generated by Django 2.0 on 2018-01-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='lote_corral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='ganado.Lote'),
        ),
    ]
