# Generated by Django 2.0.1 on 2018-01-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='arete_siniga',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='cuarto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='numero_semana',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='cuarto',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='numero_semana',
        ),
        migrations.AddField(
            model_name='peso',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesadas', to='ganado.Animal'),
        ),
    ]
