# Generated by Django 2.0.1 on 2018-10-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0002_auto_20180819_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastoanimal',
            options={'ordering': ['-created']},
        ),
    ]
