# Generated by Django 2.0.1 on 2018-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0002_auto_20180116_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='arete_siniga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(blank=True, choices=[('becerro', 'becerro'), ('toro', 'toro'), ('vaca', 'vaca'), ('vaquilla', 'vaquilla')], max_length=100, null=True),
        ),
    ]
