# Generated by Django 2.0.1 on 2018-01-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0002_auto_20180123_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='corral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='ganado.Corral'),
        ),
    ]
