# Generated by Django 2.0 on 2018-01-06 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0002_auto_20180106_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='lote_corral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='ganado.Lote'),
        ),
    ]
