# Generated by Django 2.0.1 on 2018-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_auto_20180116_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corral',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
