# Generated by Django 2.0.1 on 2018-11-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_auto_20181021_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoanimal',
            name='insumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gastoanimal',
            name='insumo_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastoanimal',
            name='insumo_q',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastoanimal',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
