# Generated by Django 2.0.1 on 2018-01-08 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_remove_animal_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliments', to='ganado.Animal'),
        ),
    ]
