# Generated by Django 2.0.1 on 2018-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_auto_20180124_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
