# Generated by Django 2.0.1 on 2018-01-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0004_alimento_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='lote_corral',
            new_name='lote',
        ),
    ]
