# Generated by Django 2.0.1 on 2019-01-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0004_auto_20181126_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='days_in_ranch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salenote',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
