# Generated by Django 2.0.1 on 2018-01-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_auto_20180109_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ano',
            field=models.PositiveIntegerField(blank=True, default=2010, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cuarto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mes',
            field=models.CharField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_semana',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
