# Generated by Django 2.0.1 on 2018-01-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_auto_20180124_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='comentarios',
        ),
    ]
