# Generated by Django 2.0.1 on 2018-01-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_auto_20180118_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='corral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='ganado.Corral'),
        ),
    ]
