# Generated by Django 2.0.1 on 2019-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_auto_20190117_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='conversion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='kg_hechos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
