# Generated by Django 2.0.1 on 2018-01-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0006_remove_animal_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoanimal',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
