# Generated by Django 2.0.1 on 2018-01-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0006_auto_20180109_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='ganado.Lote'),
        ),
    ]
