# Generated by Django 2.0.1 on 2019-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0007_auto_20190122_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='costo_por_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='days_in_ranch',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
