# Generated by Django 2.0.1 on 2018-02-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0008_auto_20180129_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arete_rancho',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
