# Generated by Django 2.0.1 on 2019-01-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0008_auto_20190123_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='costo_por_dia',
            new_name='cdp',
        ),
        migrations.AddField(
            model_name='animal',
            name='gdp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
