# Generated by Django 2.0.1 on 2019-01-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0009_auto_20190123_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='cdp',
            new_name='costo_por_dia',
        ),
    ]
