# Generated by Django 2.0.1 on 2018-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0009_auto_20180206_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arete_rancho',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
