# Generated by Django 2.0.1 on 2019-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0010_auto_20190123_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='otromas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
