# Generated by Django 2.0.1 on 2018-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0010_auto_20180206_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(max_length=130),
        ),
    ]
