# Generated by Django 2.0.1 on 2019-01-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0011_animal_otromas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='gdp',
            new_name='ganacia_diaria_promedio',
        ),
    ]
