# Generated by Django 2.0.1 on 2018-02-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0012_auto_20180206_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corral',
            name='numero_serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
