# Generated by Django 2.0.1 on 2018-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0013_auto_20180208_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='corral',
            name='no_corral',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
