# Generated by Django 2.0.1 on 2018-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0014_auto_20180208_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='merma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
