# Generated by Django 2.0.1 on 2018-02-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0016_auto_20180227_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='numero_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
