# Generated by Django 2.0.1 on 2018-03-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_auto_20180308_2254'),
        ('planta_alimentos', '0008_auto_20180214_1836'),
        ('ganado', '0019_animal_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoanimal',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_animal', to='planta_alimentos.Formula'),
        ),
        migrations.AddField(
            model_name='gastoanimal',
            name='vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_animal', to='vacunas.Vacuna'),
        ),
    ]
