# Generated by Django 2.0.1 on 2018-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0021_gastoanimal_unity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-id']},
        ),
    ]
