# Generated by Django 2.0.1 on 2018-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0022_auto_20180313_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='no_corral',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
