# Generated by Django 2.0.1 on 2018-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0025_auto_20180327_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoanimal',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
