# Generated by Django 2.0.1 on 2018-05-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0027_auto_20180510_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ref_factura_original',
        ),
        migrations.AddField(
            model_name='animal',
            name='ref_factura_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='ganado.Factura'),
        ),
    ]
