# Generated by Django 2.0.1 on 2018-08-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposicion',
            old_name='saldo',
            new_name='monto',
        ),
    ]
