# Generated by Django 2.0.1 on 2018-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_auto_20180827_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposicion',
            name='gracia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='disposicion',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
