# Generated by Django 2.0.1 on 2018-10-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_auto_20181003_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(db_index=True)),
                ('disposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='creditos.Disposicion')),
            ],
        ),
    ]
