# Generated by Django 2.0.1 on 2018-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposicion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
