# Generated by Django 2.0.1 on 2018-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_disposicion_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='disposicion',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
