# Generated by Django 2.0.1 on 2018-10-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_auto_20181021_2238'),
        ('creditos', '0006_auto_20181015_1621'),
    ]

    operations = [
    ]
