# Generated by Django 2.0.1 on 2018-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_auto_20181021_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
    ]
