# Generated by Django 2.0.1 on 2018-11-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20181023_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['fecha']},
        ),
    ]
