# Generated by Django 2.0.1 on 2018-10-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20181023_0030'),
        ('creditos', '0007_merge_20181022_1435'),
    ]

    operations = [
    ]
