# Generated by Django 2.0.1 on 2018-11-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_merge_20181023_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['fecha']},
        ),
    ]
