# Generated by Django 2.0.1 on 2018-11-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_auto_20181112_1857'),
        ('creditos', '0008_auto_20181126_0454'),
    ]

    operations = [
    ]
