# Generated by Django 2.0.1 on 2018-11-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_auto_20181108_1753'),
        ('creditos', '0008_auto_20181126_0454'),
    ]

    operations = [
    ]
