# Generated by Django 2.0.1 on 2019-01-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_merge_20181130_0013'),
        ('creditos', '0010_merge_20181126_1622'),
    ]

    operations = [
    ]
